[logging]
loglevel = INFO

[data_collection]
collection_name =
account =
index = default
interval = 300
request_timeout = 30
collect_qtrees = 1
interval_qtrees = 300
collect_aggregates = 1
interval_aggregates = 300
collect_volume = 1
interval_volume = 300
collect_svms = 1
interval_svms = 300
collect_cluster_nodes = 1
interval_cluster_nodes = 300
collect_cluster_identity = 1
interval_cluster_identity = 300
